baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Paume'
theme = ["flexion", "hugo-cite"]

enableInlineShortcodes = true
relativeURLs = true
canonifyURLs = true
removePathAccents=true

[params]
 subtitle = "Site de « Recherche-Création sur l'épaisseur de l'écriture »"
 date-depot = "2023-12-01"
 bibtex_file = "content/bib/bibtex.bib"

[params.themes]
  nevrose = "Névrose"
  petites_mains = "Petites mains"
  media = "Média"
  geste = "Geste"
  matiere = "Matière"

[permalinks]
  pages = "/:filename"

[markup]
  [markup.goldmark]
    typographer = true
    [markup.goldmark.renderer]
     footnoteReturnLinkContents = "&uarr;"
      unsafe = true


[menu]
  [[menu.main]]
    name = "Au creux"
    pre = "home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Doigts de la main"
    pre = "pages"
    url = "/pages"
    weight = 2
  [[menu.main]]
    name = "Articulations des phalanges"
    pre = "structure"
    url = "/structure/"
    weight = 3   
  [[menu.main]]
    name = "Chutes"
    pre = "chutes"
    url = "/chutes/"
    weight = 4 
  [[menu.main]]
    name = "Dans les plis"
    pre = "credits"
    url = "/credits/"
    weight = 6

[author]
    name = ""
    email = ""
